### ISSUE TITLE
looks like the script it fell, guys

### ISSUE THREAD

**Issue by tomatowithsalt1** [ilytobias/Khan-Destroyer#12]
### Describe the bug

![Screenshot_20241004_160050_Chrome](https://github.com/user-attachments/assets/9a28e323-d470-4bc6-a061-4e20981b98d7)

### Steps to reproduce

```bash
I do it on my laptop and my cell phone. I saw some tutorials and it worked, but suddenly it doesn't work anymore, and it's not just mine that's like this.    :c
```

### Operating System

macOS

### Browser

Microsoft Edge

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest build).

**Comment by luidj010** [comment]
o meu está assim também

**Comment by ilytobias** [comment]
will fix soon
