### ISSUE TITLE
None of the bookmark methods worked 

### ISSUE THREAD

**Issue by cayard** [ilytobias/Khan-Destroyer#13]
### Describe the bug

Every time I try to use one of the bookmarks this pops up 
![Screenshot 2024-10-05 075336](https://github.com/user-attachments/assets/4eb3833c-4a8a-4bfd-afd1-a41a2b03f636)

### Steps to reproduce

```bash
.
```

### Are you stupid

Maybe

### Operating System

Windows

### Browser

Chrome

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest build).

**Comment by ilytobias** [comment]
I know burh ill fix today
