### ISSUE TITLE
Khan blocks userscript

### ISSUE THREAD

**Issue by FreshPhp** [ilytobias/Khan-Destroyer#9]
### Describe the bug

Now when I have the extension active the site does not release the question and says that there was an error.

### Steps to reproduce

```bash
After activating the browser extension and restarting the page, the error appears
```

### Operating System

Windows

### Browser

Microsoft Edge

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest build).

**Comment by Matecen** [comment]
Eu achei muito bom
